// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcsltqkCQIXRrCMw-LAh7W8u-WF_QYCSQ',
    appId: '1:348338311029:web:a6d4dfa556749853368d3c',
    messagingSenderId: '348338311029',
    projectId: 'chatapp-flutter-46db3',
    authDomain: 'chatapp-flutter-46db3.firebaseapp.com',
    storageBucket: 'chatapp-flutter-46db3.appspot.com',
    measurementId: 'G-5NMFYBEE9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-AmHz3f58Q02v18vg31mMx4Obw5NcJg',
    appId: '1:348338311029:android:a7987f8b2047a913368d3c',
    messagingSenderId: '348338311029',
    projectId: 'chatapp-flutter-46db3',
    storageBucket: 'chatapp-flutter-46db3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT3cRopzsu2sP-yVRgNApumpM32DCqrmI',
    appId: '1:348338311029:ios:eab63ddadf20b947368d3c',
    messagingSenderId: '348338311029',
    projectId: 'chatapp-flutter-46db3',
    storageBucket: 'chatapp-flutter-46db3.appspot.com',
    iosClientId: '348338311029-i8drscip28c7fn5qu91pkit14b2vf7v1.apps.googleusercontent.com',
    iosBundleId: 'com.atul.chatappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT3cRopzsu2sP-yVRgNApumpM32DCqrmI',
    appId: '1:348338311029:ios:eab63ddadf20b947368d3c',
    messagingSenderId: '348338311029',
    projectId: 'chatapp-flutter-46db3',
    storageBucket: 'chatapp-flutter-46db3.appspot.com',
    iosClientId: '348338311029-i8drscip28c7fn5qu91pkit14b2vf7v1.apps.googleusercontent.com',
    iosBundleId: 'com.atul.chatappFlutter',
  );
}
